apiVersion: v1
kind: Service
metadata:
  name: book-store
  labels:
    app: book-store
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30010
      protocol: TCP
      name: http
  selector:
    app: book-store
