apiVersion: v1
kind: Service
metadata:
  name: book-store
  labels:
    app: book-store
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 300005
  selector:
    app: book-store